<?php
// auto-generated by sfPropelCrud
// date: 2008/08/07 20:31:37
?>
<?php use_helper('Object', 'Validation') ?>

<div id="pageHeader">
	<h2><?php echo link_to(__("The Kollaborator!"), '/collaboration'); ?></h2>
	<p class="subtitle"><?php echo __("Colaborative work is great, isn't it?"); ?></p>
</div>


<div id="pageContent">

	<div class="contentBox light alignLeft">
		<?php echo form_tag('collaboration/update') ?>
		
		<?php echo object_input_hidden_tag($collaboration_offer, 'getId') ?>
		
		<p class="noSpace"><?php echo label_for('title', __('Title:')); ?></p>
		<?php echo form_error("title"); ?>
		<?php echo object_input_tag($collaboration_offer, 'getTitle', array (
		  'size' => 55, 'maxlength' => 75
		)) ?>
		<br/>
		<br/>
		<p class="noSpace"><?php echo label_for('description', __('Description:')); ?></p>
		<?php echo form_error('description'); ?>
		<?php echo object_textarea_tag($collaboration_offer, 'getDescription', array (
		  'size' => '60x5',
		)) ?>
		<br/>
		<br/>
		<p class="noSpace"><?php echo label_for('tags', __('What are you looking for? (tags)')); ?></p>
		<?php echo form_error('tags'); ?>
		<?php echo object_input_tag($collaboration_offer, 'getTagsString', array (
		  'size' => 55,
		)) ?>
		<br/>
		<br/>
		<?php echo submit_tag('save') ?>
		<?php if ($collaboration_offer->getId()): ?>
		  &nbsp;<?php echo link_to('cancel', 'collaboration/show?id='.$collaboration_offer->getId()) ?>
		<?php else: ?>
		  &nbsp;<?php echo link_to('cancel', 'collaboration/list') ?>
		<?php endif; ?>
		
		</form>
	</div>
	
	<div class="contentBox alignLeft fixedWidth half">
		<h3 class="header"><?php echo __('Write a cool collaboration offer:'); ?>
	</div>

</div>