<?php
// auto-generated by sfPropelCrud
// date: 2008/08/07 20:31:37
?>
<h1>collaborations</h1>

<table>
<thead>
<tr>
  <th>Created by</th>
  <th>Created at</th>
  <th>Updated at</th>
  <th>Title</th>
  <th>Description</th>
  <th>Id</th>
</tr>
</thead>
<tbody>
<?php foreach ($collaboration_offers as $collaboration_offer): ?>
<tr>
    <td><?php echo $collaboration_offer->getCreatedBy() ?></td>
      <td><?php echo $collaboration_offer->getCreatedAt() ?></td>
      <td><?php echo $collaboration_offer->getUpdatedAt() ?></td>
      <td><?php echo $collaboration_offer->getTitle() ?></td>
      <td><?php echo $collaboration_offer->getDescription() ?></td>
      <td><?php echo link_to($collaboration_offer->getId(), 'collaboration/show?id='.$collaboration_offer->getId()) ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('create', 'collaboration/create') ?>
