# default values
all:
  version: "Beta 1"
  register:
    daystovalidate: 7
  apikeylength: 12 # este valor debe ser igual al de la base de datos
  dir:
    asset:   "assets"
    game:    "UploadedGames"
    widget:  "UploadedWidgets"
    avatarPiece: "UploadedPieces"
    groupIcons:  "GroupIcons"
    competitionIcons:  "CompetitionIcons"

  pager:
    profile: 12
    collaboration: 20
    recipe: 15

  sf_guard_plugin:
     remember_key_expiration_age:  2592000   # 30 days in seconds
     remember_cookie_name:         ululandRememberMe

  sfPropelActAsCommentableBehaviorPlugin:
    allowed_tags:
      a:              <a>
      blockquote:     <blockquote>
      code:           <code>
      em:             <em>
      i:              <i>
      p:              <p>
      strong:         <strong>
    anonymous:
      enabled:        false
      layout:
        name:         required
        email:        required
        website:      optional
        title:        optional
        comment:      required
      name:           Anonymous User
    css:              false
    count:
      enabled:        true
      method:         setSfCommentCount
      namespace:      frontend
    date_format:      words
    hide_form:        true
    namespaces:
      backend:        administrator
    use_ajax:         true
    use_gravatar:     true
    user:
      enabled:        true
      layout:
#        title:        optional
        comment:      required
      table:          sf_guard_user
      id:             id
      class:          sfGuardUser
      id_method:      getId
      toString:       __toString