rendering: ~
web_debug: ~
security:
#  class: sfGuardBasicSecurityFilter

# generally, you will want to insert your own filters here
sf_syntax_highlighter_plugin:
  class: sfSyntaxHighlighterFilter
ul_custom_filter:
  class: ulCustomFilter
  
cache:     ~
common:    ~
flash:     ~
execution: ~
