# code recipes

recipe_list:
  url: /recipes
  param: { module: recipe, action: list }

recipe_list_tag:
  url: /recipes/tag/:tag
  param: { module: recipe, action: list }
  
recipe_list_search:
  url: /recipes/search/:search
  param: { module: recipe, action: list }
  
recipe_show:
  url: /recipes/:title
  param: { module: recipe, action: show }

recipe_edit:
  url: /recipes/:title/edit
  param: { module: recipe, action: edit }
  
# collaboration offers

collaboration_index:
  url: /collaborations/index
  param: { module: collaboration, action: index }
  
collaboration_list:
  url: /collaborations
  param: { module: collaboration, action: list }

collaboration_list_tag:
  url: /collaborations/tag/:tag
  param: { module: collaboration, action: list }
  
collaboration_list_search:
  url: /collaborations/search/:search
  param: { module: collaboration, action: list }
  
collaboration_show:
  url: /collaborations/:title
  param: { module: collaboration, action: show }

collaboration_edit:
  url: /collaborations/:title/edit
  param: { module: collaboration, action: edit }
  
# profiles

user_list:
  url: /people
  param: { module: profile, action: list }

user_list_tag:
  url: /people/tag/:tag
  param: { module: profile, action: list }

user_list_search:
  url: /people/search/:search
  param: { module: profile, action: list }
  
user_show:
  url: /people/:username
  param: { module: profile, action: show }

user_edit:
  url: /people/:username/edit
  param: { module: profile, action: edit }
  
  
# various

latest_news_ajax:
  url: /latest_news
  param: { module: home, action: latestNews }

# Authentification
register:
  url: /register
  param: { module: sfGuardAuth, action: register }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
