default:
  http_metas:
    content-type: text/html

  metas:
    title:        Red de desarrolladores de Ululand
    robots:       index, follow
    description:  Red de desarrolladores de Ululand
    keywords:     ululand, flash development, desarrollo, flash, desarrolladores, developers
    language:     es

  stylesheets:    [main]

  javascripts:    [behaviors]

  has_layout:     on
  layout:         layout
