default:
  http_metas:
    content-type: text/html

  metas:
    title:        Flash Game Developers Community - developers.ululand.com
    robots:       index, follow
    description:  Red de desarrolladores de Ululand
    keywords:     ululand, flash development, desarrollo, flash, desarrolladores, developers, desarrollo juegos flash, comunidad desarrolladores, flash games development
    language:     es

  stylesheets:    [main, geshi]

  javascripts:    [behaviors]

  has_layout:     on
  layout:         layout
