default:
  http_metas:
    content-type: text/html

  metas:
    title:        ululand admin
    robots:       noindex, nofollow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [main, prototip]

  javascripts:    [prototip]

  has_layout:     on
  layout:         layout
