generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      AvatarPiece
    theme:            default
    
    edit:
      display: [id, name, description, author_id, owner_id, upload, url, price, type, in_use, created_at]
      fields:
        url: {params: disabled=true}
        upload:            
          type:        admin_input_file_tag
          upload_dir:  UploadedParts
          filename:    %%name%%
          params:      include_link=UploadedParts include_remove=true
      
