generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      GameStat
    theme:            default
    
    edit:
      fields:
        uuid:
          params: disabled=true
        stripped_name:
          params: disabled=true
