generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Avatar_Group
    theme:            default

    fields:
      grupo_id:         {name: Grupo}
      avatar_id:        {name: Avatar}
      is_owner:         {name: Propietario}
      is_approved:      {name: Admitido}

    list:
      title: Listado de la relacion de grupos y avatares
      display: [id, grupo_id, avatar_id, is_owner, is_approved]
      filters: [id, grupo_id, avatar_id, is_owner, is_approved]
      object_actions:
        _edit:      ~
        _delete:    ~
        
    edit:
      title: Editar una relacion grupo avatar
      display: [id, grupo_id, avatar_id, is_owner, is_approved]