ApproveEmailSuccess:
  layout: isolatedLayout
ResendApprovalEmailSuccess:
  layout: isolatedLayout
ResendApprovalEmailError:
  layout: isolatedLayout
LoginSuccess:
  layout: isolatedLayout
RegisterSuccess:
  layout: isolatedLayout