generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Group
    theme:            default
    
    fields:
      id:
      name:              {name: Nombre}
      description:       {name: Descripci&oacute;n}

    list:
      title: Listado de grupos
      display: [id, name, description]
      filters: [id, name, description]
      object_actions:
        _edit:      ~
        _delete:    ~
        
    edit:
      title: Editar un grupo
      display: [id, name, description]