generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Account
    theme:            default
    
    fields:
      hashedpassword:    {params: display=true}
      created_at:        {name: Fecha de Creaci&oacute;n}
      confirmation_date: {name: Fecha de Confirmaci&oacute;n}
      account_level:     {name: Privilegios}
      sessionid:         {name: Sesi&oacute;n}
      password:          {name: Contrase&ntilde;a, params: disabled=false}

    list:
      title: Listado de todas las cuentas
      display: [id, email, hashedpassword, salt, created_at, confirmation_date, account_level, sessionid]
      filters: [id, email, created_at, confirmation_date, account_level, sessionid]
      object_actions:
        _edit:      ~
        _delete:    ~
        
    edit:
      title:          Edicion de cuentas
      display: [email, password, created_at, confirmation_date, account_level, sessionid]