generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Item
    theme:            default

    fields:
      name:              { name: Nombre del objeto }
      id_itemtype:       { name: Tipo del objeto }
      url:               { name: Direcci&oacute;n de la imagen, params: disabled=true }
      description:       { name: Descripci&oacute;n del objeto }
      upload:            { name: Subir imagen, params: disabled=false }
      open:              { name: Abrir imagen }
      itype:             { name: Tipo de objeto, params: disabled=false }
      image:             { name: Imagen }
      price:             { name: Precio }
      
    list:
      title: Listado de todos los objetos
      display: [id, name, gender, id_itemtype, itype, _linked_url, description, price]
      filters: [id, name, _gender, id_itemtype, url, description, price]
      object_actions:
        _edit:       ~        
        customdelete: {name: Eliminar imagen, action: customDelete}

    edit:
      title:          Edicion de objetos
      fields:
        url:               { params: disabled=true }
        upload:            
          type:        admin_input_file_tag
          upload_dir:  assets
          filename:    %%id%%
          params:      include_link=assets include_remove=true
      display: [name, id_itemtype, _gender, _image, upload, open, url, description, price]

