default:
  http_metas:
    content-type: text/html

  metas:
    title:        ululand.com - Juegos, amigos, competiciones y diversión.
    robots:       index, follow
    description:  ululand es un portal de juegos sociales
    keywords:     ululand
    language:     es
    encoding:     utf8

  stylesheets:    [positions, appearance, colors, prototip]

  javascripts: [prototip, behaviors]
  

  has_layout:     on
  layout:         layout
