generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Competition
    theme:            default
    
    edit:
      fields:
        stripped_name:
          params: disabled=true
        thumbnail_path:
          type:       admin_input_file_tag 
          upload_dir: CompetitionIcons
          filename:   %%stripped_name%%
