<?php
// auto-generated by sfPropelCrud
// date: 2008/02/21 12:09:13
?>
<?php


/**
 * game actions.
 *
 * @package    PFC
 * @subpackage game
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class gameActions extends sfActions
{
  
  public function executeIndex()
  {
    return $this->forward('game', 'list');
  }

  public function executeList()
  {
    	$tag = $this->getRequestParameter('tag');
		if($tag)
		{
			$this->tag = $tag;
		}
  		$search = $this->getRequestParameter('search');
		if($search)
		{
			$this->search = $search;
		}
  }

  public function executeShow()
  {
  	if($this->getRequestParameter('id'))
  	{
  		$game = GamePeer::retrieveByPk($this->getRequestParameter('id'));
  		$this->redirect('game/show?stripped_name='.$game->getStrippedName());
  	}
  	else if($this->getRequestParameter('stripped_name'))
  	{
  		$c = new Criteria();
  		$c->add(GamePeer::STRIPPED_NAME, $this->getRequestParameter('stripped_name'));
  		$this->game = GamePeer::doSelectOne($c);
  	}

  	$this->forward404Unless($this->game);

  	// Aumentar en uno las partidas jugadas del juego
  	$this->game->incrementCounter();

  	// Cargar los gamestats del juego para mostrarlos en el template
  	$this->gamestats = $this->game->getGameStats();
  }

}
