default:
  http_metas:
    content-type: text/html

  metas:
    title:        Ululand.com - Play Social 
    robots:       index, follow
    description:  Ululand.com is a free, flash games portal mixed with a vertical social network of flash game players. Also, it has a whole section dedicated exclusively to developers. 
    keywords:     flash game, browser game, free flash game, social network, flash games development, juego flash, juegos flash, juegos gratis, red social, desarrollo de juegos flash
    language:     es

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
