generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Avatar_Item
    theme:            default
    
    fields:
      id_avatar:         {name: Avatar}
      id_item:           {name: Objeto}
      active:            {name: Activo}

    list:
      title: Listado de la relación de avatares y objetos