<?php
// auto-generated by sfPropelCrud
// date: 2008/07/23 19:55:02
?>
<?php use_helper('Object') ?>
<div id="pageHeader">
	<h2><?php echo __("Edit your profile"); ?></h2>

</div>

<div id="pageContent">
	<?php echo form_tag('profile/update') ?>
	
	<?php echo object_input_hidden_tag($sf_guard_user_profile, 'getId') ?>
	
	<div class="fixedWidth half alignLeft contentBox bordered">
		<div class="">
			<h3 class="header"><?php echo __('Developer Data'); ?></h3>
			<p class=""><?php echo __('Url'); ?></p>
			<?php echo object_input_tag($developerProfile, 'getUrl', array (
			  'size' => 25,
			)) ?>
			<p class=""><?php echo __('Tags'); ?></p>
			<?php echo object_input_tag($developerProfile, 'getTagsString', array (
			  'size' => 35,
			)) ?>
			<p class=""><?php echo __('Searching a project to work on?'); ?>
			<?php echo object_checkbox_tag($developerProfile, 'getIsFree', array (
			  
			)) ?> </p>
		</div>
		<div class="">
			<h3 class="header"><?php echo __('Developer Information'); ?></h3>
			<p class=""><?php echo __('Write whatever you want. Accepts Markdown.'); ?></p>
			<?php echo object_textarea_tag($developerProfile, 'getDescription', array (
			  'rows' => 12,
			  'cols' => 55
			)) ?>
		</div>
	</div>
	<div class="fixedWidth half alignRight">
		<div class="contentBox bordered">
			<h3 class="header"><?php echo __('General Data'); ?></h3>
			<p class=""><?php echo __('Username'); ?></p>
			<?php echo object_input_tag($sf_guard_user_profile, 'getUsername', array (
			  'size' => 20,
			)) ?>
			<p class=""><?php echo __('Language'); ?></p>
			<?php echo select_language_tag('culture', null, array('languages' => array('es', 'en'))); ?>
		</div>
	</div>
	<div style="clear:both"></div>
	<div class="contentBox" style="text-align: center">
		<?php echo submit_tag(__('save')) ?>
		<?php if ($sf_guard_user_profile->getId()): ?>
		  &nbsp;<?php echo link_to(__('cancel'), 'profile/show?id='.$sf_guard_user_profile->getId()) ?>
		<?php else: ?>
		  &nbsp;<?php echo link_to(__('cancel'), 'profile/list') ?>
		<?php endif; ?>
	</div>
	</form>
</div>