<?php
// auto-generated by sfPropelCrud
// date: 2008/07/23 19:55:02
?>
<div id="pageHeader">
	<h2><?php echo __("Registered people"); ?></h2>
	<p class="subtitle"><?php echo __("We create games!"); ?></p>
</div>

<div id="pageContent">

	<?php if($sf_user->isAuthenticated() && !$sf_user->getProfile()->isFilledIn()) { ?>
		<div class="fixedWidth third alignRight contentBox bordered">
			<h3 class="header"><?php echo link_to(__("Fill in your profile now!"), 'profile/edit?id='.$sf_user->getProfile()->getId()); ?></h3>
			<p class=""><?php echo __("Your profile is not filled in and you will not be listed here."); ?></p>
			<p class=""><?php echo link_to(__("Fill in your profile &raquo;"), 'profile/edit?id='.$sf_user->getProfile()->getId()); ?></p>
		</div>
	<?php } ?>
	<?php foreach ($sf_guard_user_profiles as $sf_guard_user_profile): ?>
		<?php if($sf_guard_user_profile->isFilledIn()) { ?>
			<div class="alignCenter fixedWidth quarter contentBox">
				<?php echo link_to($sf_guard_user_profile, "profile/show?username=".$sf_guard_user_profile->getUsername(), array('class' => 'button alignCenter')); ?>
			</div>
		<?php } ?>
	<?php endforeach; ?>

</div>