<?php
// auto-generated by sfPropelCrud
// date: 2008/07/23 19:55:02
?>
<div id="pageHeader">
	<!-- <h2>
		<?php echo link_to($sf_guard_user_profile, 'profile/show?username='.$sf_guard_user_profile->getUsername()); ?>

	</h2> -->
	<h2>
		<?php echo linkToProfileWithGravatar($sf_guard_user_profile, 70); ?>
		<?php if($sf_user->isAuthenticated() && $sf_guard_user_profile->getId() == $sf_user->getProfile()->getId()) { ?> 
			<span class="">(<?php echo linkToEditProfile($sf_guard_user_profile); ?>)</span>
		<?php } ?>
	</h2>
</div>
	
<div id="pageContent">

	<div class="contentColumn wide alignLeft">
		<div class="contentBox bordered">
			
			
			<?php if($playerProfile->getDescription() != ''){ ?> 
				<?php echo sfMarkdown::doConvert( $playerProfile->getDescription() ); ?>
			<?php } else { ?>
				<p><?php echo __('There is no description for this user'); ?></p>
			<?php } ?>
			
			<?php if($sf_user->isAuthenticated() && $sf_guard_user_profile->getId() == $sf_user->getProfile()->getId()) { ?> 
				<span class="small"><?php echo linkToEditProfile($sf_guard_user_profile); ?></span>
			<?php } ?>
		</div>
	</div>
	
	<div class="clearFloat"></div>
	
	<div class="contentColumn quarter contentBox alignCenter">
		<?php echo link_to(sprintf('&laquo; %s', __('List')), 'profile/list', array('class' => 'button')) ?>
	</div>

</div>