# default values
all:
  version: "Alfa 6"
  register:
    daystovalidate: 7
  saltlength: 4
  pager:
    profile: 12
    game:    12
  dir:
    asset:       "assets"
    game:        "UploadedGames"
    widget:      "UploadedWidgets"
    avatarPiece: "UploadedPieces"
    groupIcons:  "GroupIcons"
    competitionIcons:  "CompetitionIcons"
  
  rating:
    user_id_getter:      [myUser, getConnectedAvatarId] 
    
  sfPropelActAsCommentableBehaviorPlugin:
    allowed_tags:
      a:              <a>
      blockquote:     <blockquote>
      code:           <code>
      em:             <em>
      i:              <i>
      p:              <p>
      strong:         <strong>
    anonymous:
      enabled:        false
      layout:
        name:         required
        email:        required
        website:      optional
        title:        optional
        comment:      required
      name:           Anonymous User
    css:              false
    count:
      enabled:        true
      method:         setSfCommentCount
      namespace:      frontend
    date_format:      words
    hide_form:        true
    namespaces:
      backend:        administrator
    use_ajax:         true
    use_gravatar:     true
    user:
      enabled:        true
      layout:
#        title:        optional
        comment:      required
      table:          sf_guard_user
      id:             id
      class:          sfGuardUser
      id_method:      getId
      toString:       __toString