# default values
all:
  version: "Alfa 6"
  register:
    daystovalidate: 7
  saltlength: 4
  pager:
    profile: 12
    game:    12
  dir:
    asset:       "assets"
    game:        "UploadedGames"
    widget:      "UploadedWidgets"
    avatarPiece: "UploadedPieces"
    groupIcons:  "GroupIcons"
  
  rating:
    user_id_getter:      [myUser, getConnectedAvatarId] 
    
  sfSimpleForumPlugin:
    forum_name:              Foros de Ululand
    display_categories:      true
    use_feeds:               false  # requires sfFeed2Plugin
    count_views:             true  # count each time a topic is viewed. Turn off to increase performance
    max_per_block:           10    # maximum number of links displayed in a block
    include_breadcrumb:      true  # include breadcrumb slot content. Turn off if you don't use the breadcrumb.
    breadcrumb_separator:    ' &raquo; ' # separator for breadcrumb trail
    max_per_page:            10    # maximum threads or messages per page
    pages_displayed:         5     # maximum pages displayed by the pager navigation
    feed_max:                10    # maximum messages served by feed
    show_author_details:     true # display number of messages of post authors
    allow_new_topic_outside_forum: true
    user_class:              Account         # name of the class used to manage users
    retrieve_by_name_method: retrieveByUsername  # name of the static method used to retrieve a user by its username
    
  sfPropelActAsCommentableBehaviorPlugin:
    allowed_tags:
      a:              <a>
      blockquote:     <blockquote>
      code:           <code>
      em:             <em>
      i:              <i>
      p:              <p>
      strong:         <strong>
    anonymous:
      enabled:        false
      layout:
        name:         required
        email:        required
        website:      optional
        title:        optional
        comment:      required
      name:           Anonymous User
    css:              false
    count:
      enabled:        true
      method:         setSfCommentCount
      namespace:      frontend
    date_format:      words
    hide_form:        true
    namespaces:
      backend:        administrator
    use_ajax:         true
    use_gravatar:     true
    user:
      enabled:        true
      layout:
#        title:        optional
        comment:      required
      table:          sf_guard_user
      id:             id
      class:          sfGuardUser
      id_method:      getId
      toString:       __toString