
# Games

game_list:
  url: /games
  param: { module: game, action: list }

game_list_tag:
  url: /games/tag/:tag
  param: { module: game, action: list }

game_list_search:
  url: /games/search/:search
  param: { module: game, action: list }

game_show:
  url: /games/:stripped_name
  param: { module: game, action: show }

game_embed:
  url: /games/:g/embed
  param: { module: game, action: embed }

# profiles

user_list:
  url: /people
  param: { module: profile, action: list }

user_list_tag:
  url: /people/tag/:tag
  param: { module: profile, action: list }

user_list_search:
  url: /people/search/:search
  param: { module: profile, action: list }
  
user_show:
  url: /people/:username
  param: { module: profile, action: show }

# Authentification

register:
  url:   /register
  param: { module: sfGuardAuth, action: register }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# Options

options:
  url: /options
  param: { module: options, action: index }

options_edit_profile:
  url: /options/editProfile
  param: { module: options, action: editProfile }

options_change_password:
  url: /options/changePassword
  param: { module: options, action: editPassword }

options_edit_settings:
  url: /options/editSettings
  param: { module: options, action: editSettings }

options_edit_avatar:
  url: /options/editAvatar
  param: { module: options, action: editAvatar }

# default rules
homepage:
  url:   /
  param: { module: home, action: Welcome }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*