# SfGuardAuth

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# Messages and comments
add_message:
  url:   /add_message
  param: { module: message, action: add }
add_comment:
  url:   /add_comment
  param: { module: comment, action: add }
  
  
# default rules
homepage:
  url:   /
  param: { module: home, action: Welcome }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*