# Authentification

register:
  url:   /register
  param: { module: sfGuardAuth, action: register }
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

# Options

options:
  url: /options
  param: { module: options, action: index }

options_edit_profile:
  url: /options/editProfile
  param: { module: options, action: editProfile }

options_change_password:
  url: /options/changePassword
  param: { module: options, action: editPassword }

options_edit_settings:
  url: /options/editSettings
  param: { module: options, action: editSettings }

options_edit_avatar:
  url: /options/editAvatar
  param: { module: options, action: editAvatar }

# Messages and comments
add_message:
  url:   /add_message
  param: { module: message, action: add }
add_comment:
  url:   /add_comment
  param: { module: comment, action: add }
  
  
# default rules
homepage:
  url:   /
  param: { module: home, action: Welcome }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*