<?php
// auto-generated by sfPropelCrud
// date: 2008/10/11 16:06:39
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $avatar_piece->getId() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $avatar_piece->getName() ?></td>
</tr>
<tr>
<th>Description: </th>
<td><?php echo $avatar_piece->getDescription() ?></td>
</tr>
<tr>
<th>Author: </th>
<td><?php echo $avatar_piece->getAuthorId() ?></td>
</tr>
<tr>
<th>Owner: </th>
<td><?php echo $avatar_piece->getOwnerId() ?></td>
</tr>
<tr>
<th>Url: </th>
<td><?php echo $avatar_piece->getUrl() ?></td>
</tr>
<tr>
<th>Price: </th>
<td><?php echo $avatar_piece->getPrice() ?></td>
</tr>
<tr>
<th>Type: </th>
<td><?php echo $avatar_piece->getType() ?></td>
</tr>
<tr>
<th>In use: </th>
<td><?php echo $avatar_piece->getInUse() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $avatar_piece->getCreatedAt() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'avatarPiece/edit?id='.$avatar_piece->getId()) ?>
&nbsp;<?php echo link_to('list', 'avatarPiece/list') ?>
