generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Widget
    theme:            default
    
    fields:
      api_key:           {name: Clave API}
      privileges_level:  {name: Privilegios }
      name:              {name: Nombre}
      description:       {name: Descripci&oacute;n}
      url:               {name: Direcci&oacute;n del juego, params: disabled=true}
      width:             {name: Ancho}
      height:            {name: Alto}   
      bgcolor:           {name: Color}
      upload:            {name: Subir, params: disabled=false}
      
    list:
      title: Listado de todos los widgets
      display: [id, api_key, privileges_level, name, description, url, width, height, bgcolor]
      filters: [id, privileges_level, name, description, url, width, height, bgcolor]
      object_actions:
        _edit:      ~        
        _delete:    ~

    edit:
      title:          Editar un widget
      fields:
        api_key:           { params: disabled=true }
        url:               {params: disabled=true}
        upload:            
          type:        admin_input_file_tag
          upload_dir:  UploadedWidgets/%%name%%
          filename:    %%name%%
          params:      include_link=UploadedWidgets include_remove=true
          required:    true
      display: [id, api_key, privileges_level, name, description, url, upload, width, height, bgcolor]