generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      PlayerProfile
    theme:            default

    fields:
      id:
      description:       {name: Descripcion}
      total_credits:     {name: Créditos totales}
      available_credits: {name: Créditos disponibles}

    list:
      title: Listado de jugadores
      display: [id, description, total_credits, available_credits]
      filters: [id, total_credits, available_credits]
      object_actions:
        _edit:      ~
        _delete:    ~
        
    edit:
      title: Editar un jugador
      display: [description, total_credits, available_credits]