generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Game
    theme:            default
    
    fields:
      api_key:           {name: Clave API}
      privileges_level:  {name: Privilegios }
      name:              {name: Nombre}
      description:       {name: Descripci&oacute;n}
      thumbnail_path:    {name: Icono}
      url:               {name: Direcci&oacute;n del juego, params: disabled=true}
      width:             {name: Ancho}
      height:            {name: Alto}   
      bgcolor:           {name: Color}
      upload:            {name: Subir juego, params: disabled=false}
      gameplays:         {name: Partidas jugadas, params: disabled=false}
      _tags:             {name: Etiquetas}
      
    list:
      title: Listado de todos los juegos
      display: [id, api_key, privileges_level, name, description, thumbnail_path, url, width, height, bgcolor, gameplays]
      filters: [id, privileges_level, name, _tags]
      object_actions:
        _edit:      ~        
        _delete:    ~

    edit:
      title:          Edicion de juegos
      fields:
        api_key:           {params: disabled=true}
        url:               {params: disabled=true}
        thumbnail_path:    {params: disabled=true}
        upload_thumbnail:
          type:        admin_input_file_tag
          upload_dir:  UploadedGames/%%name%%
          filename:    thumbnail
          params:      include_link=UploadedGames include_remove=true
        upload:            
          type:        admin_input_file_tag
          upload_dir:  UploadedGames/%%name%%
          filename:    %%name%%
          params:      include_link=UploadedGames include_remove=true
          required:    true
      display: [id, api_key, privileges_level, name, description, _tags, thumbnail_path, upload_thumbnail, url, upload, width, height, bgcolor, gameplays]